refactor: simplify conditional statements
- Used && for conciseness

diff --git a/down-ext-file b/down-ext-file
--- a/down-ext-file
+++ b/down-ext-file
@@ -10,14 +10,10 @@ if [[ -f "${file}" ]]; then
   # Attempt to read JSON file contents
   extensions="$(jq -r '.[]' "${file}" 2>/dev/null)"
 
-  if [[ $? -ne 0 ]]; then
-    log-error "Failed to parse '${file}'"
-  fi
+  [[ $? -ne 0 ]] && log-error "Failed to parse '${file}'"
 
   # Create extensions directory if it does not exist
-  if [[ ! -d "extensions" ]]; then
-    mkdir "extensions"
-  fi
+  [[ ! -d "extensions" ]] && mkdir "extensions"
 else
   log-error "File '${file}' not found."
 fi
diff --git a/install-ext-online b/install-ext-online
--- a/install-ext-online
+++ b/install-ext-online
@@ -11,17 +11,16 @@ trap 'rm -f $file' EXIT
 
 get-ext "${file}" -o &>/dev/null
 
-if [[ ! -s "${origin}" ]]; then
+[[ ! -s "${origin}" ]] && {
   log-warning "No entries found in ${origin}" || exit 0
-fi
+}
 
 if [[ -s "${file}" ]]; then
   # Combine JSON files with only unique enteries as an array
   extensions="$(jq -s 'flatten' "${origin}" "${file}" | get-unique | sed 's/, *]/]/' | jq -r '.[]')"
 
-  if [[ $? -ne 0 ]]; then
-    log-error "Failed to parse '${file}'"
-  fi
+  [[ $? -ne 0 ]] && log-error "Failed to parse '${file}'"
+
 else
   log-warning "No new entries found in ${file}" || exit 0
 fi
