fix: handle jq parse errors more gracefully
- improve error checking in file parsing

diff --git a/down-ext-file b/down-ext-file
--- a/down-ext-file
+++ b/down-ext-file
@@ -29,9 +29,9 @@ file="${1:-'extensions.json'}"
 
 if [[ -f "${file}" ]]; then
   # Attempt to read JSON file contents
-  extensions="$(jq -r '.[]' "${file}" 2>/dev/null)"
-
-  [[ $? -ne 0 ]] && log-error "Failed to parse '${file}'"
+  if ! extensions="$(jq -r '.[]' "${file}" 2>/dev/null)"; then
+    log-error "Failed to parse '${file}'"
+  fi
 
   # Create extensions directory if it does not exist
   [[ ! -d "extensions" ]] && mkdir "extensions"
diff --git a/install-ext-online b/install-ext-online
--- a/install-ext-online
+++ b/install-ext-online
@@ -39,9 +39,9 @@ get-ext "${file}" -o &>/dev/null
 
 if [[ -s "${file}" ]]; then
   # Combine JSON files with only unique enteries as an array
-  extensions="$(jq -s 'flatten' "${origin}" "${file}" | get-unique | sed 's/, *]/]/' | jq -r '.[]')"
-
-  [[ $? -ne 0 ]] && log-error "Failed to parse '${file}'"
+  if ! extensions="$(jq -s '[.[][]] | unique | .[]' -r "${origin}" "${file}")"; then
+    log-error "Failed to parse '${file}'"
+  fi
 
 else
   log-warning "No new entries found in ${file}" || exit 0
