fix: add trap for SIGUSR1 in scripts
- Added trap 'exit 1' SIGUSR1 to handle signal interruptions

diff --git a/down-ext-file b/down-ext-file
--- a/down-ext-file
+++ b/down-ext-file
@@ -2,42 +2,44 @@
 
 set -euo pipefail
 
+trap 'exit 1' SIGUSR1
+
 file="${1:-'extensions.json'}"
 
 if [[ -f "${file}" ]]; then
-	# Attempt to read JSON file contents
-	extensions="$(jq -r '.[]' "${file}" 2>/dev/null)"
+  # Attempt to read JSON file contents
+  extensions="$(jq -r '.[]' "${file}" 2>/dev/null)"
 
-	if [[ $? -ne 0 ]]; then
-		log-error "Failed to parse '${file}'"
-	fi
+  if [[ $? -ne 0 ]]; then
+    log-error "Failed to parse '${file}'"
+  fi
 
-	# Create extensions directory if it does not exist
-	if [[ ! -d "extensions" ]]; then
-		mkdir "extensions"
-	fi
+  # Create extensions directory if it does not exist
+  if [[ ! -d "extensions" ]]; then
+    mkdir "extensions"
+  fi
 else
-	log-error "File '${file}' not found."
+  log-error "File '${file}' not found."
 fi
 
 for extension in ${extensions}; do
-	publisher=$(echo "${extension}" | cut -d '.' -f 1)
-	extensionName=$(echo "${extension}" | cut -d '.' -f 2)
-	url="https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extensionName}/latest/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
+  publisher=$(echo "${extension}" | cut -d '.' -f 1)
+  extensionName=$(echo "${extension}" | cut -d '.' -f 2)
+  url="https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extensionName}/latest/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
 
-	# Construct the filename for the .vsix file
-	filename="${extensionName}.vsix"
+  # Construct the filename for the .vsix file
+  filename="${extensionName}.vsix"
 
-	# Check if the file already exists in the directory
-	if [[ -f "${PWD}/extensions/${filename}" ]]; then
-		log-warning "Skipping ${filename}. File already exists."
-	else
-		# Download the .vsix file with only the progress bar shown
-		if ! wget -q --show-progress -O "${PWD}/extensions/${filename}" "${url}"; then
-			log-error "Failed to download ${filename}."
-		fi
-		log-info "Downloaded ${filename}"
-	fi
+  # Check if the file already exists in the directory
+  if [[ -f "${PWD}/extensions/${filename}" ]]; then
+    log-warning "Skipping ${filename}. File already exists."
+  else
+    # Download the .vsix file with only the progress bar shown
+    if ! wget -q --show-progress -O "${PWD}/extensions/${filename}" "${url}"; then
+      log-error "Failed to download ${filename}."
+    fi
+    log-info "Downloaded ${filename}"
+  fi
 done
 
 log-success "Done 🚀"
diff --git a/get-ext b/get-ext
--- a/get-ext
+++ b/get-ext
@@ -2,42 +2,44 @@
 
 set -euo pipefail
 
+trap 'exit 1' SIGUSR1
+
 getExtensions() {
-	# Get all VS Code extensions
-	extensions="$(code --list-extensions)"
+  # Get all VS Code extensions
+  extensions="$(code --list-extensions)"
 
-	# Format the extensions for the JSON file
-	readarray -t array <<<"${extensions}"
+  # Format the extensions for the JSON file
+  readarray -t array <<<"${extensions}"
 
-	# Create the JSON content
-	printf '%s\n' "${array[@]}" | jq -R . | jq -s .
+  # Create the JSON content
+  printf '%s\n' "${array[@]}" | jq -R . | jq -s .
 }
 
 file="${1:-'extensions.json'}"
 
 # Check if the file already exists
 if [[ -f "${file}" ]]; then
-	if [[ $1 == "-o" || $2 == "-o" ]]; then
-		eval getExtensions >"${file}"
-		log-info "${file} has been overwritten."
-	elif [[ $1 == "" || $2 == "" ]]; then
-		overwrite='n'
-		log-warning "${file} exists do you want to overwrite it? (y/N): "
-		read -r overwrite
-		if [[ ${overwrite} == "y" || ${overwrite} == "Y" ]]; then
-			eval getExtensions >"${file}"
-			log-info "${file} has been overwritten."
-		elif [[ ${overwrite} == "n" || ${overwrite} == "N" || ${overwrite} == "" ]]; then
-			log-info "Original file was not overwritten."
-			exit 0
-		else
-			log-error "Invalid option!"
-		fi
-	else
-		log-error "Invalid option!"
-	fi
+  if [[ $1 == "-o" || $2 == "-o" ]]; then
+    eval getExtensions >"${file}"
+    log-info "${file} has been overwritten."
+  elif [[ $1 == "" || $2 == "" ]]; then
+    overwrite='n'
+    log-warning "${file} exists do you want to overwrite it? (y/N): "
+    read -r overwrite
+    if [[ ${overwrite} == "y" || ${overwrite} == "Y" ]]; then
+      eval getExtensions >"${file}"
+      log-info "${file} has been overwritten."
+    elif [[ ${overwrite} == "n" || ${overwrite} == "N" || ${overwrite} == "" ]]; then
+      log-info "Original file was not overwritten."
+      exit 0
+    else
+      log-error "Invalid option!"
+    fi
+  else
+    log-error "Invalid option!"
+  fi
 else
-	touch "${file}"
-	eval getExtensions >"${file}"
-	log-info "${file} has been created."
+  touch "${file}"
+  eval getExtensions >"${file}"
+  log-info "${file} has been created."
 fi
diff --git a/install-ext b/install-ext
--- a/install-ext
+++ b/install-ext
@@ -2,6 +2,8 @@
 
 set -euo pipefail
 
+trap 'exit 1' SIGUSR1
+
 directory="${1:-extensions}"
 
 # Change to the extensions directory
@@ -9,14 +11,14 @@ cd "${directory}" || log-error "${directory} was not found!"
 
 # Loop through all .vsix files in the extensions directory
 for extension in *.vsix; do
-	if [[ -f ${extension} ]]; then
-		# Install the extension using VSCode CLI
-		if ! code --install-extension "${extension}"; then
-			log-error "Error: Failed to install ${extension}."
-		fi
-	else
-		log-error "No .vsix files found in ${directory}."
-	fi
+  if [[ -f ${extension} ]]; then
+    # Install the extension using VSCode CLI
+    if ! code --install-extension "${extension}"; then
+      log-error "Error: Failed to install ${extension}."
+    fi
+  else
+    log-error "No .vsix files found in ${directory}."
+  fi
 done
 
 log-success "Installation Done 🚀"
diff --git a/mdmath b/mdmath
--- a/mdmath
+++ b/mdmath
@@ -2,10 +2,12 @@
 
 set -euo pipefail
 
+trap 'exit 1' SIGUSR1
+
 # Check if the correct number of arguments is passed
 if [[ $# -ne 1 ]]; then
-	echo "Usage: $0 <file>"
-	exit 1
+  echo "Usage: $0 <file>"
+  exit 1
 fi
 
 # Assign arguments to variables for clarity
@@ -13,7 +15,7 @@ file="$1"
 
 # Check if the file exists
 if [[ ! -f ${file} ]]; then
-	log-error "Error: File '${file}' does not exist."
+  log-error "Error: File '${file}' does not exist."
 fi
 
 # Initialize replacement counts
@@ -23,10 +25,10 @@ count=$((count_1 + count_2))
 
 # Perform the replacements
 sed -i -e 's~\\\[~$$~g' \
-	-e 's~\\\]~$$~g' \
-	-e 's~ \\)~$~g' \
-	-e 's~\\( ~$~g' \
-	-e 's~\\(~$~g' \
-	-e 's~\\)~$~g' "${file}"
+  -e 's~\\\]~$$~g' \
+  -e 's~ \\)~$~g' \
+  -e 's~\\( ~$~g' \
+  -e 's~\\(~$~g' \
+  -e 's~\\)~$~g' "${file}"
 
 log-success "${count} Replacements made"
