refactor: add set -euo pipefail to scripts
- Added error handling
- Improved script reliability

diff --git a/get-unique b/get-unique
--- a/get-unique
+++ b/get-unique
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
 backup=0
 
 while getopts "b" opt; do
@@ -60,7 +62,6 @@ else
     cat "${tmpfile}" >"${file}"
     log-info "Removed all non-unique entries!"
   else
-    log-error "Error: ${file} was not found!" >&2
-    exit 1
+    log-error "Error: ${file} was not found!"
   fi
 fi
diff --git a/install-ext-online b/install-ext-online
--- a/install-ext-online
+++ b/install-ext-online
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
 origin="$1"
 
 file=$(mktemp -t "XXXXXX.json")
@@ -16,7 +18,7 @@ if [[ -s "${file}" ]]; then
   extensions="$(jq -s 'flatten' "${origin}" "${file}" | get-unique | sed 's/, *]/]/' | jq -r '.[]')"
 
   if [[ $? -ne 0 ]]; then
-    log-error "Failed to parse '${file}'" || exit 1
+    log-error "Failed to parse '${file}'"
   fi
 else
   log-warning "No new entries found in ${file}" || exit 0
