refactor(utils): improve unique entries handling
- Handle stdin and file input in getUnique
- Add installExtOnline script for extensions
- Improve noDuplicates script
- Use temporary files for better error handling
- Add logging for better feedback

diff --git a/getUnique b/getUnique
--- a/getUnique
+++ b/getUnique
@@ -1,12 +1,11 @@
 #!/usr/bin/env bash
 
 file="$1"
+tmpfile="$(mktemp)"
+trap 'rm -f $tmpfile' EXIT
 
-if [[ -f $file ]]; then
-  tmpfile="$(mktemp)"
-  trap 'rm -f $tmpfile' EXIT
-
-  # Count occurrences and keep order
+if [[ -z ${file} || ${file} == "-" ]]; then
+  # Read from stdin
   awk '
     {
       count[$0]++
@@ -17,12 +16,28 @@ if [[ -f $file ]]; then
         if (count[lines[i]] == 1) print lines[i]
       }
     }
-  ' "$file" > "$tmpfile"
-
-  # Overwrite original file
-  cat "$tmpfile" > "$file"
-
-  log-info "Removed all non-unique entries"
+  ' >"${tmpfile}"
+  # print the output to the stdout
+  cat "${tmpfile}"
 else
-  log-error "Error: $file not found!"
+  # Read from {file}
+  if [[ -f ${file} ]]; then
+    awk '
+      {
+        count[$0]++
+        lines[NR] = $0
+      }
+      END {
+        for (i = 1; i <= NR; i++) {
+          if (count[lines[i]] == 1) print lines[i]
+        }
+      }
+    ' "${file}" >"${tmpfile}"
+    # override the input file
+    cat "${tmpfile}" >"${file}"
+    log-info "Removed all non-unique entries!"
+  else
+    log-error "${file} was not found!"
+    exit 1
+  fi
 fi
diff --git a/noDuplicates b/noDuplicates
--- a/noDuplicates
+++ b/noDuplicates
@@ -1,16 +1,23 @@
 #!/usr/bin/env bash
 
 file="$1"
+tmpfile="$(mktemp)"
+trap 'rm -f $tmpfile' EXIT
 
-if [[ -f $file ]]; then
-  tmpfile="$(mktemp)"
-  trap 'rm -f $tmpfile' EXIT
-  
-  awk '!x[$0]++' "$file" >"$tmpfile"
-
-  cat "$tmpfile" >"$file"
-
-  log-info "Duplicates removed!"
+if [[ -z ${file} || ${file} == "-" ]]; then
+  # Read from stdin
+  awk '!x[$0]++' > "${tmpfile}"
+  cat "${tmpfile}"
 else
-  log-error "$file was not found!"
+  # Read from {file}
+  if [[ -f ${file} ]]; then
+    awk '!x[$0]++' "${file}" > "${tmpfile}"
+    cat "${tmpfile}" > "${file}"
+    log-info "Duplicates removed!"
+  else
+    log-error "${file} was not found!"
+    exit 1
+  fi
 fi
+
+
