chore: improve gitsync script robustness
- Improved error handling and quoting.
- Enhanced branch handling logic.
- Fixed potential issues with variable expansion.
- Updated shellcheck rules.
- Improved script readability.

diff --git a/gitsync b/gitsync
--- a/gitsync
+++ b/gitsync
@@ -3,8 +3,8 @@
 # returns true if it's a git repo and false otherwise
 isGitRepo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
 
-if [[ -z $isGitRepo ]]; then
-  log-error "$PWD is not a git repository." || exit
+if [[ -z ${isGitRepo} ]]; then
+  log-error "${PWD} is not a git repository." || exit
 fi
 
 timestamp="$(date +"%Y-%m-%d@%I:%M%p")"
@@ -29,18 +29,18 @@ main() {
 
   git commit -am "Updated Files ${timestamp}" && log-info "Committed Changes Locally ${timestamp}"
 
-  git push origin "$branch" && log-success "Changes pushed to $branch successfully!"
+  git push origin "${branch}" && log-success "Changes pushed to ${branch} successfully!"
 }
 
 # Check if no options are passed
-if [ $# -eq 0 ]; then
+if [[ $# -eq 0 ]]; then
   # returns the current working branch
   branch="$(git rev-parse --abbrev-ref HEAD)"
 fi
 
 # Use getopts to parse options
 while getopts "hb" opt 2>/dev/null; do
-  case $opt in
+  case ${opt} in
   h)
     display_help
     exit 0
@@ -49,14 +49,17 @@ while getopts "hb" opt 2>/dev/null; do
     if [[ -z "$2" ]]; then
       log-error "You must pass a branch when using -b option."
     else
-      if [[ "$branch" != "$2" ]]; then
-        git checkout "$branch"
+      if [[ "${branch}" != "$2" ]]; then
+        git checkout "${branch}"
       fi
       branch="$2"
     fi
     ;;
   \?)
-    log-error "Invalid option $OPTARG"
+    log-error "Invalid option ${OPTARG}"
+    ;;
+  *)
+    log-error "Invalid option ${OPTARG}"
     ;;
   esac
 done
