feat: add --safe mode to prevent non-zero exit
- adds --safe mode to prevent non-zero exit
- avoids breaking existing scripts

diff --git a/is-git-repo b/is-git-repo
--- a/is-git-repo
+++ b/is-git-repo
@@ -24,10 +24,36 @@ trap 'exit 1' SIGUSR1
 source check-deps
 checkDeps "$0"
 # ---  Main script logic --- #
-# returns true if it's a git repo and false otherwise
-isGitRepo=$(git rev-parse --is-inside-work-tree 2>/dev/null) || log-error "${PWD} is not a git repository."
+logRed() {
+  # read from stdin
+  if [[ $# -eq 0 || $1 == "-" ]]; then
+    str=$(cat)
+  else
+    str="$*"
+  fi
 
-# check if the user is inside .git directory
-[[ ${isGitRepo} != true ]] && log-error "Not in a work tree."
+  # Print error message in red
+  tput setaf 1
+
+  echo -e "[ERROR] ${str}" 1>&2
+  tput sgr0
+
+  # Exit with failure code
+  exit 1
+}
+
+if [[ "${1:-none}" == "--safe" ]]; then
+  # returns true if it's a git repo and false otherwise
+  isGitRepo=$(git rev-parse --is-inside-work-tree 2>/dev/null) || logRed "${PWD} is not a git repository."
+
+  # check if the user is inside .git directory
+  [[ ${isGitRepo} != true ]] && logRed "Not in a work tree."
+else
+  # returns true if it's a git repo and false otherwise
+  isGitRepo=$(git rev-parse --is-inside-work-tree 2>/dev/null) || log-error "${PWD} is not a git repository."
+
+  # check if the user is inside .git directory
+  [[ ${isGitRepo} != true ]] && log-error "Not in a work tree."
+fi
 
 exit 0
