feat: read log message from stdin
- Read from stdin if no args

diff --git a/log-error b/log-error
--- a/log-error
+++ b/log-error
@@ -1,8 +1,16 @@
 #!/usr/bin/env bash
 
+# read from stdin
+if [[ $# -eq 0 || $1 == "-" ]]; then
+  str=$(cat)
+else
+  str="$*"
+fi
+
 # Print error message in red
 tput setaf 1
-echo -e "[ERROR]: $*" >&2
+
+echo -e "[ERROR]: ${str}" 1>&2
 tput sgr0
 
 # Get parent PID (script that called log-error) and send SIGUSR1
