refactor: improve script generation
- Use printf for consistent output
- Inline check-deps call in make-signature

diff --git a/make-signature b/make-signature
--- a/make-signature
+++ b/make-signature
@@ -16,6 +16,7 @@
 # --- DEPENDENCIES --- #
 # - toilet
 # - sed
+# - printf
 # --- END SIGNATURE --- #
 
 set -euo pipefail
@@ -29,8 +30,7 @@ name="$1"
 desc="$2"
 deps="$3"
 
-echo "#!/usr/bin/env bash"
-echo ""
+printf "#!/usr/bin/env bash\n\n"
 echo "# --- SCRIPT SIGNATURE --- #"
 
 toilet --font mono12 --termwidth --width 190 "${name}" | sed 's/^/# /'
@@ -47,13 +47,13 @@ else
   done
 fi
 
-echo "# --- END SIGNATURE --- #"
-echo ""
+printf "# --- END SIGNATURE --- #\n\n"
 
-echo "set -euo pipefail"
-echo ""
-echo "trap 'exit 1' SIGUSR1"
-echo ""
-echo "check-deps \"$0\""
-# ---  Main script logic --- #"
-echo ""
+printf "set -euo pipefail\n\n"
+
+printf "trap 'exit 1' SIGUSR1\n\n"
+
+echo 'source check-deps'
+echo 'checkDeps "$0"'
+
+printf "# ---  Main script logic --- #\n\n"
