chore: improve script argument parsing
- use cmdarg for consistent arg handling
- add quiet mode to mdclean
- improve error handling in mdfmt

diff --git a/md2docx b/md2docx
--- a/md2docx
+++ b/md2docx
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+#
 # --- SCRIPT SIGNATURE --- #
 #
 #                  ▄▄   ▄▄▄▄▄          ▄▄
@@ -18,23 +18,26 @@
 # - sed
 # --- END SIGNATURE --- #
 
-set -euo pipefail
-
+set -eo pipefail
 trap 'exit 1' SIGUSR1
 
+eval "$(include "lib/cmdarg.sh")"
 eval "$(include "check-deps")"
+
 checkDeps "$0"
+cmdarg_info "header" "$(get-desc "$0")"
+cmdarg_parse "$@"
 # ---  Main script logic --- #
-file="$1"
+file="${argv[0]}"
 
 if [[ -f "${file}" ]]; then
   # This removes everything after the last dot, including the dot
   filename="${file%.*}"
 
-  if [[ -z "${MRT}" && -f ${MRT} ]]; then
-    pandoc "${file}" -o "${filename}.docx" || log-error "Unknown Error Occured"
-  else
+  if [[ -n "${MRT}" && -f "${MRT}" ]]; then
     pandoc "${file}" -o "${filename}.docx" --reference-doc="${MRT}" || log-error "Unknown Error Occured"
+  else
+    pandoc "${file}" -o "${filename}.docx" || log-error "Unknown Error Occured"
   fi
 
   log-success "File '${file}' converted successfully!"
diff --git a/mdfmt b/mdfmt
--- a/mdfmt
+++ b/mdfmt
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+#
 # --- SCRIPT SIGNATURE --- #
 #
 #                  ▄▄     ▄▄▄▄
@@ -19,35 +19,37 @@
 # - prettier
 # --- END SIGNATURE --- #
 
-set -euo pipefail
-
+set -eo pipefail
 trap 'exit 1' SIGUSR1
 
+eval "$(include "lib/cmdarg.sh")"
 eval "$(include "check-deps")"
 checkDeps "$0"
+
+cmdarg_info "header" "$(get-desc "$0")"
+cmdarg_parse "$@"
 # ---  Main script logic --- #
 declare -a files
 
-if [[ $# -eq 0 || $1 == "." ]]; then
+if [[ "${argv[0]}" == "." ]] || ((argc == 0)); then
   # Populate the array directly from fd output
   mapfile -t files < <(fd . -e md -e markdown --hidden)
 else
-  for file in "$@"; do
+  for file in "${argv[@]}"; do
     ext=$(echo "${file}" | awk -F. '{print $NF}')
     [[ "${ext}" == "md" || "${ext}" == "markdown" ]] && files+=("${file}")
   done
 fi
 
+# NOTE: ((0)) fails, while any other number succeeds
+((${#files[@]})) || log-error "No valid markdown files were passed"
+
 for file in "${files[@]}"; do
-  mdclean "${file}" &>/dev/null
+  mdclean "${file}" --quiet || log-warning "Failed to clean '${file}'"
 
   sed -e "s|[‘’]|'|g" \
     -e 's|[“”]|"|g' \
     -i "${file}"
 done
 
-if [[ ${#files[@]} -eq 0 ]]; then
-  log-error "No valid markdown files were passed"
-else
-  prettier --write --config "${PRETTIERRC}" "${files[@]}"
-fi
+prettier --write --config "${PRETTIERRC}" "${files[@]}"
