Updated Files 2024-12-08@01:22PM

diff --git a/mdmath b/mdmath
--- a/mdmath
+++ b/mdmath
@@ -1,33 +1,38 @@
 #!/usr/bin/env bash
 
-# shellcheck source=/dev/null
 source logs.sh
 
 # Check if the correct number of arguments is passed
-if [ "$#" -ne 1 ]; then
-  echo "Usage: $0 <file>"
-  exit 1
+if [[ $# -ne 1 ]]; then
+	echo "Usage: $0 <file>"
+	exit 1
 fi
 
 # Assign arguments to variables for clarity
 file="$1"
 
 # Check if the file exists
-if [ ! -f "$file" ]; then
-  log_error "Error: File '$file' does not exist."
+if [[ ! -f ${file} ]]; then
+	log_error "Error: File '${file}' does not exist."
 fi
 
-# Initialize replacement counts
-count_1=$(grep -o '\\\[' "$file" | wc -l)
-count_2=$(grep -o '\\(' "$file" | wc -l)
+# Count occurrences of '\['
+count_1=$(grep -o '\\[' "${file}")
+count_1=$(wc -l "${count_1}")
+
+# Count occurrences of '\('
+count_2=$(grep -o '\\(' "${file}")
+count_2=$(wc -l "${count_2}")
+
+# Sum the counts
 count=$((count_1 + count_2))
 
 # Perform the replacements
 sed -i -e 's~\\\[~$$~g' \
-  -e 's~\\\]~$$~g' \
-  -e 's~ \\)~$~g' \
-  -e 's~\\( ~$~g' \
-  -e 's~\\(~$~g' \
-  -e 's~\\)~$~g' "$file"
+	-e 's~\\\]~$$~g' \
+	-e 's~ \\)~$~g' \
+	-e 's~\\( ~$~g' \
+	-e 's~\\(~$~g' \
+	-e 's~\\)~$~g' "${file}"
 
-log_info "$count Replacements made"
+log_info "${count} Replacements made"
