feat: Add file creation options to mkscript
- Add temp file creation
- Add file in current directory
- Improve error messages

diff --git a/mkscript b/mkscript
--- a/mkscript
+++ b/mkscript
@@ -4,11 +4,51 @@ set -euo pipefail
 
 trap 'exit 1' SIGUSR1
 
-name=$(gum input --placeholder "Enter Script's name: ")
+# Store option values
+temp_flag=0
+file_flag=0
+no_flags=0
 
-[[ -f ${name} ]] && log-error "The scripts ${name} already exists at $(whereis ${name})!"
+# Parse options
+while getopts "ft" opt; do
+  case "${opt}" in
+  f)
+    file_flag=1
+    ;;
+  t)
+    temp_flag=1
+    ;;
+  ?)
+    no_flags=1
+    ;;
+  *)
+    log-error "Invalid option: -${OPTARG}"
+    ;;
+  esac
+done
 
-file="${SCRIPTS_DIR}/${name}"
+# # Shift past the options to handle remaining arguments
+# shift $((OPTIND - 1))
+
+if [[ "${temp_flag}" -eq 1 ]]; then
+  file=$(mktemp -t XXXXX-script.sh)
+  name="$(basename "${file}")"
+  trap 'rm -f $file' EXIT
+
+elif [[ "${file_flag}" -eq 1 ]]; then
+  name=$(gum input --placeholder "Enter Script's name: ")
+  file="${PWD}/${name}"
+
+  if [[ "${name}" != *.sh ]]; then
+    gum confirm "Do you want to add .sh extension to your script?" && file="${PWD}/${name}.sh"
+  fi
+
+elif [[ "${no_flags}" -eq 1 ]]; then
+  name=$(gum input --placeholder "Enter Script's name: ")
+  file="${SCRIPTS_DIR}/${name}"
+fi
+
+[[ -f "${file}" && "${temp_flag}" -eq 0 ]] && log-error "The script '${name}' already exists at '${file}'!"
 
 touch "${file}" || log-error "Failed to create file '${file}'"
 
@@ -23,7 +63,7 @@ EOF
 
 echo "${text}" >"${file}"
 
-chmod u+x "${file}" || log-error "Failed to make file '${file}' executable"
+chmod u+x "${file}" || log-error "Failed to make '${name}' executable"
 
 "${EDITOR}" "${file}"
 
